features:
    - buildpack-stack=ubuntu-22
spec:
  name: steam-microtransaction-api
  services:
    - name: microtransaction-api
      git:
        branch: main
        repo_clone_url: https://github.com/skyrusfx/steam-microtransaction-api.git
      envs:
        - key: STEAM_WEBKEY
          value: 'E9F09C45B9393D2DCA25FCEEEE028B18'
          type: SECRET
        - key: STEAM_CURRENCY
          value: 'USD'
          type: SECRET
        - key: STEAM_ITEM_LOCALE
          value: 'en'
          type: SECRET
